apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inbound-parse-deployment
spec:
  selector:
    matchLabels:
      app: inbound-parse
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: inbound-parse
    spec:
      containers:
      - name: inbound-parse
        image: inbound-parse-docker:latest
        imagePullPolicy: IfNotPresent # enables pull from local system
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inbound-parse-svc
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: inbound-parse
  type: LoadBalancer
