apiVersion: v1
kind: Service
metadata:
  name: inbound-parse-svc
  namespace: inbound-parse
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: inbound-parse
  type: LoadBalancer