root: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
env:
  es6: true
  node: true
  mocha: true
  jasmine: true
rules:
  linebreak-style:
    - error
    - unix
  max-len:
    - warn
    - code: 80
      tabWidth: 2
      ignoreComments: true
      ignoreUrls: true
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        let: 2
        const: 3
  semi:
    - error
    - always
  consistent-this:
    - error
    - self
    - $ctrl
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  new-cap:
    - error
    - newIsCap: true
      capIsNew: true
      properties: false
  array-bracket-spacing:
    - error
    - never
  arrow-spacing:
    - error
    - before: true
      after: true
  block-spacing:
    - error
    - always
  comma-spacing:
    - error
    - before: false
      after: true
  computed-property-spacing:
    - error
    - never
  generator-star-spacing:
    - error
    - before: true
      after: false
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: minimum
  keyword-spacing:
    - error
    - before: true
  semi-spacing:
    - error
    - before: false
      after: true
  space-in-parens:
    - error
    - never
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  space-before-function-paren:
    - error
    - never
  space-before-blocks:
    - error
    - always
  yoda:
    - error
    - never
  wrap-iife:
    - error
    - outside
  eqeqeq:
    - error
    - always
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 3
  one-var-declaration-per-line:
    - error
    - initializations
  brace-style:
    - error
    - stroustrup
  no-implicit-coercion:
    - error
    - boolean: false
  no-multiple-empty-lines:
    - error
    - max: 1
  eol-last: error
  dot-notation: error
  space-infix-ops: error
  no-with: error
  no-unreachable: error
  no-redeclare: error
  no-unexpected-multiline: error
  no-multi-spaces: error
  no-multi-str: error
  no-trailing-spaces: error
  no-mixed-spaces-and-tabs: error
  no-spaced-func: error
  no-whitespace-before-property: error
  no-lonely-if: error
  no-console: off

  # Possible Errors
  no-await-in-loop: off
  no-cond-assign: error
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-empty: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: off
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations:
    - error
    - functions
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-prototype-builtins: off
  no-regex-spaces: error
  no-sparse-arrays: error
  no-unsafe-finally: off
  no-unsafe-negation: off
  use-isnan: error
  valid-jsdoc: off
  valid-typeof: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: off
  block-scoped-var: off
  class-methods-use-this: off
  complexity:
    - error
    - 6
  consistent-return: off
  default-case: off
  dot-location: off
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: off
  no-empty-function: off
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: off
  no-fallthrough: error
  no-floating-decimal: off
  no-global-assign: off
  no-implied-eval: error
  no-invalid-this: off
  no-iterator: error
  no-labels:
    - error
    - allowLoop: true
      allowSwitch: true
  no-lone-blocks: error
  no-loop-func: error
  no-magic-number: off
  no-native-reassign: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-octal: error
  no-param-reassign: off
  no-proto: error
  no-restricted-properties: off
  no-return-assign: error
  no-return-await: off
  no-script-url: error
  no-self-assign: off
  no-self-compare: error
  no-sequences: off
  no-throw-literal: off
  no-unmodified-loop-condition: off
  no-unused-expressions: error
  no-unused-labels: off
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: off
  no-useless-return: off
  no-void: error
  no-warning-comments: off
  prefer-promise-reject-errors: off
  radix: error
  require-await: off
  vars-on-top: off

  # Strict
  strict: off

  # Variables
  init-declarations: off
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow-restricted-names: error
  no-shadow: off
  no-undef-init: error
  no-undef: off
  no-undefined: off
  no-unused-vars: off
  no-use-before-define: off

  # Node.js and CommonJS
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-mixed-requires: off
  no-new-require: off
  no-path-concat: error
  no-process-env: off
  no-process-exit: error
  no-restricted-modules: off
  no-sync: off

  # Stylistic Issues
  camelcase: off
  capitalized-comments: off
  comma-style: off
  func-call-spacing: off
  func-name-matching: off
  func-names: off
  func-style: off
  id-length: off
  id-match: off
  jsx-quotes: off
  line-comment-position: off
  lines-around-comment: off
  lines-around-directive: off
  max-depth: off
  max-nested-callbacks: off
  max-params: off
  max-statements-per-line: off
  max-statements:
    - error
    - 30
  multiline-ternary: off
  new-parens: off
  newline-after-var: off
  newline-before-return: off
  no-array-constructor: off
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-mixed-operators: off
  no-multi-assign: off
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: off
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-underscore-dangle: off
  no-unneeded-ternary: off
  object-property-newline: off
  one-var: off
  operator-assignment: off
  operator-linebreak: off
  padded-blocks: off
  quote-props: off
  require-jsdoc: off
  sort-keys: off
  sort-vars: off
  spaced-comment: off
  template-tag-spacing: off
  unicode-bom: off
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style: off
  arrow-parens: off
  constructor-super: off
  no-class-assign: off
  no-confusing-arrow: off
  no-const-assign: off
  no-dupe-class-members: off
  no-duplicate-imports: off
  no-new-symbol: off
  no-restricted-imports: off
  no-this-before-super: off
  no-useless-computed-key: off
  no-useless-constructor: off
  no-useless-rename: off
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-rest-params: off
  prefer-reflect: off
  prefer-spread: off
  prefer-template: off
  require-yield: off
  rest-spread-spacing: off
  sort-imports: off
  symbol-description: off
  yield-star-spacing: off
