env:
  es6: true
  node: true
  mocha: true
  jasmine: true
rules:
  array-bracket-spacing:
  - 2
  - never
  - {}
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: true
  camelcase: 0
  comma-dangle:
  - 2
  - always-multiline
  comma-spacing:
  - 2
  - after: true
    before: false
  comma-style:
  - 2
  - last
  curly:
  - 2
  - all
  dot-notation: 0
  eol-last: 2
  indent:
  - 2
  - 2
  - SwitchCase: 1
  key-spacing:
  - 2
  - afterColon: true
    beforeColon: false
  keyword-spacing:
  - 2
  - {}
  linebreak-style:
  - 2
  - unix
  no-empty:
  - 2
  - allowEmptyCatch: true
  no-mixed-spaces-and-tabs: 2
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-with: 2
  one-var:
  - 2
  - never
  quote-props:
  - 2
  - as-needed
  quotes:
  - 2
  - single
  semi:
  - 2
  - always
  semi-spacing:
  - 2
  - after: true
    before: false
  space-before-blocks:
  - 2
  - always
  space-before-function-paren:
  - 2
  - anonymous: ignore
    named: never
  space-in-parens:
  - 2
  - never
  space-infix-ops: 2
  space-unary-ops:
  - 2
  - nonwords: false
    words: false
  wrap-iife: 2
  yoda:
  - 2
  - never
